mapbox/mapbox-gl-leaflet

- leaflet-mapbox-gl.js
Add the mapbox-gl layer to the tilePane instead of the overlayPan to avoid z-index issues. Fixes #9
> Add the mapbox-gl layer to the tilePane

- examples/basic.html
- examples/cluster.html
The examples used options.token when the plugin was looking for options.accessToken.
> Fix examples

- leaflet-mapbox-gl.js
After this obvious fix, the lib was actually broken:
https://github.com/mapbox/mapbox-gl-leaflet/commit/b0eb35e87317f754211f6af43a0f3a7bbcc87ee9
See my comments, the resize() call that was happening every time called _move() which invalidates the styles and called render.
Then update() would do basically nothing.
With the fix, if the viewport wasn't resized, calling gl.render() resulted in nothing because styles were not invalidated so mapbox-gl was doing nothing.
Instead, this PR calls update() which invalidates the style and gets the render loop working when panning / zooming.
I am not sure if it enhances performances of the map when dragging, which still lags behind but it fixes the panning issues
Tested in IE11 with latest mapbox-gl 0.7.0
Fabien
> Fix mapbox-gl rendering when panning the map

- leaflet-mapbox-gl.js
mapbox-gl-js changed from latlng to lnglat
see this commit:
https://github.com/mapbox/mapbox-gl-js/commit/1531000fd89abb793fad3495bbdc8bfb4d8c61cd
> mapbox-gl-js changed from latlng to lnglat

- leaflet-mapbox-gl.js
Hello,
Using the profiler, I noticed a memory leak when adding and removing the mapbox-gl-js layer. Here are the 3 snapshots with these 3 steps:
- Init a leaflet map with a tile layer
- Replace the tile layer with the mapbox-gl-js layer
- Replace the mapbox-gl-js layer with the original layer
Here are the results with the current version:
Here are the results after calling the remove() method onRemove:
When not calling onRemove, workers and styles are still in memory, and the resize handler is preventing the browser from deallocating the RAM.
Fabien
> Fix memory leak when removing layer

- examples/basic.html
- examples/cluster.html
I was getting 404 errors upon retrieving tiless for the bright-v7 style.
And there was a CORS error prior to updating the mapbox-gl library.
Cleaned up and recommitted so as to not commit my slop to the commit history.
> update examples (retry)

- leaflet-mapbox-gl.js
this is a small change to allow the GLMap to pan beyond min/max latitudes at low zoom levels.
> allow GLMap to pan beyond min/max latitude

- README.md
Adds a note to the README reaffirming that Mapbox will not directly support this and support requests should come through the repo. cc @mourner @danswick
> Adds "experimental" flag to README

- leaflet-mapbox-gl.js
> Set _zooming=false inside _zoomEnd() for non-animated zooms.

- examples/basic.html
- examples/cluster.html
- leaflet-mapbox-gl.js
the proposed code change would make this plugin even less picky about the underlying version of `mapbox-gl-js`.
if you're okay with the change i wouldn't have to maintain a fork of this project purely for [`esri-leaflet-vector`](https://github.com/esri/esri-leaflet-vector) anymore.
> make wrapper even more agnostic about underlying mapbox-gl version

- CHANGELOG.md
- package.json
to do:
if you're interested in automating the process of publishing releases, i could put together a PR that uses `gh-release` and a bash script to make it a one liner.
> add a project changelog and prep for 0.0.3 release

- leaflet-mapbox-gl.js
This allows developers to load the library be loaded in development workflows that use module bundlers without breaking the indicated Installation instructions in the README.
Sample Usage:
`require('mapbox-gl-leaflet/leaflet-mapbox-gl'); `
or
`import 'mapbox-gl-leaflet/leaflet-mapbox-gl'`
> Wrapped the library in a UMD wrapper.

- leaflet-mapbox-gl.js
Fixes https://github.com/mapbox/mapbox-gl-leaflet/issues/67   The new layer will properly use the **pane** option in the constructor. This allows the ability to stack layers by pane.
> support for 'pane' in constructor

- README.md
Noticed RawGit is shutting down when playing with jsfiddle, changed to unpkg instead.
> update readme cdn link

- LICENSE
- README.md
The license displayed on the repository page is `ISC`, but the in the [License section](https://github.com/mapbox/mapbox-gl-leaflet#licence) is `MIT`.
This pull request will fix the license on repository homepage.
MIT License: https://opensource.org/licenses/MIT
> Fix license typo in readme

- examples/basic.html
- examples/cluster.html
- leaflet-mapbox-gl.js
As you can see in this [example](https://jsfiddle.net/w8r/3qp1j9e6/), panning or zooming the map can produce very unpleasant flickering on around the canvas edges, something that is avoided in leaflet by using buffer tiles:
This PR addresses that issue by introducing a relative padding around the overlay containing the mapbox canvas. The arbitrary value of the padding is `0.15`, somewhat close to the value used in the leaflet vector renderers for the same purpose.
You can see the result comparison here https://bl.ocks.org/w8r/26b4f1a6ff0785a71c290d798337689a (map on the left has the padding, map on the right doesn't)
It also bumps the libraries in the examples (there was a maximum call stack exception in the basic example, rooted somewhere in the transformation update in …
> Implemented overlay padding

- API.md
- README.md
- examples/events.html
- examples/overlay.html
- leaflet-mapbox-gl.js
- fixes #101, 
- added `interactive` option
- added an example of handling `mapbox-gl` events
- added a method to get the `mapbox-gl` map
Now, you can create `L.MapboxGL` layer that will handle the built-in events, too:
```js
var gl = L.mapboxGL({
accessToken: 'no-token',
interactive: true
}).addTo(map);
var mapObject = gl.getMapboxMap();
mapObject.on('mouseenter', 'state-fills', (e) => {
console.log('state-fills mouseenter', e)
});
```
> Adds `interactive` option

- CHANGELOG.md
- leaflet-mapbox-gl.js
- package.json
> Preparing v0.0.9

- leaflet-mapbox-gl.js
The mapbox-gl-layer is currently being added to the overlayPane instead of the TilePane. It should be the latter. This issue was resolved earlier in https://github.com/mapbox/mapbox-gl-leaflet/pull/10 but reintroduced later on.
> Add mapbox-gl-layer to TilePane

- README.md
Fixes issue (similar to) 112. Also updates mapbox-gl-js to current v2.5.0, which I tested with.
> Fix script load order in README

- leaflet-mapbox-gl.js
We invoke `invalidateSize` to update the map when the map is resized. However, the mapbox canvas is not updated. So register the resize event and update mapbox canvas.
> Fix gray area when the map is resized.

- leaflet-mapbox-gl.js
I removed the check for a given access token in the options. Mapbox GL JS just works fine without if you want to use a self hosted solution.
Proof: 
https://github.com/mapbox/mapbox-gl-js/issues/8569
> Removed check for given accessToken because Mapbox GL JS works without!

- leaflet-mapbox-gl.js
just a few tweaks to:
* avoid declaring an `offset` if its not going to be used
* add a code comment for future excavators
if we wanted to be 100% safe we could instantiate a `0,0` point object and pass it through instead of relying on what [`Leaflet.DomUtil.setTransform()`](https://leafletjs.com/reference-1.7.1.html#domutil-settransform) currently does under the hood to compensate for missing/invalid input parameters, but I'm fine with what you've already proposed.
> remove unused variable and add code comment

- leaflet-mapbox-gl.js
When a zoom level is low, Mapbox.js layer and mapbox-gl-leaflet layer offset mismatch happens.
1. Create map with leaflet or Mapbox.js with empty style
2. Add GeoJSON layer
3. Add Mapbox GL JS layer with mapbox-gl-leaflet and set street-v11 style
4. Zoom out until until offset happens
[Here's](https://gist.github.com/OttyLab/50a8018c7028feac62cfd64f6cec1ece) the reproduce sample.
When `map.transform.latRange` is `null` as this [code](https://github.com/mapbox/mapbox-gl-leaflet/blob/master/leaflet-mapbox-gl.js#L133), Mapbox GL JS automatically generate offset to keep the center coordinate as the image below shows. The blue area is Mapbox GL JS canvas and offset happens when `map.transform.latRange` is `null`. However, current code tries to [subtract the …
> Fix offset issue

- leaflet-mapbox-gl.js
When the initial zoom level is low, Mapbox.js layer and mapbox-gl-leaflet layer offset mismatch happens.
1. Create map with leaflet or Mapbox.js with empty style
2. Add GeoJSON layer
3. Add Mapbox GL JS layer with mapbox-gl-leaflet and set street-v11 style
4. Set the initial zoom level low
[Here's](https://gist.github.com/OttyLab/50a8018c7028feac62cfd64f6cec1ece#file-index-mapboxjs-with-low-initial-zoom-html) the reproduce sample.
By default, Mapbox GL JS [adjusts the center and zoom level](https://github.com/mapbox/mapbox-gl-js/blob/f0cc0159819617f59bbb5c3405a13a22f2f5c704/src/geo/transform.js#L642). After [this code](https://github.com/mapbox/mapbox-gl-leaflet/blob/v0.0.13/leaflet-mapbox-gl.js#L133) is executed, the adjustment is disabled. Therefore, center and zoom needs to be recalled …
> Fix offset issue when initial zoom level is low

- leaflet-mapbox-gl.js
When re-adding a Mapbox GL layer to the Leaflet map (for example when using it in a [layers control](https://leafletjs.com/reference-1.7.1.html#control-layers)), `this._initGL();` is called again and recreates a Mapbox GL Map object from scratch `this._glMap = new mapboxgl.Map(options);`.
This means that a new SKU token is created each time the layer is added and it thus corresponds to separate map loads (which is unfortunate because [users are billed by map load](https://www.mapbox.com/pricing/#maploads)).
I updated the code to remember the Map object in `this._glMap` and only set the correct map center and zoom when the layer is re-added.
> Remember Mapbox GL map when removed to avoid creating a new SKU token on re-add

- leaflet-mapbox-gl.js
Currently, it is possible to zoom in infinitely on the maps even when maxZoom is specified.
I have now included the zoom limits with an existing L.Layer function when the layer is added.
> Apply minZoom and maxZoom options to layer
